In [1]:
import pandas as pd
import numpy as np
from top2vec import Top2Vec
import time
from scipy import stats


/share/apps/rc/software/Anaconda3/2020.07/envs/deepNLP2020/lib/python3.7/site-packages/torch/cuda/__init__.py:52: UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.)
  return torch._C._cuda_getDeviceCount() > 0


In [2]:
# Loading the saved models
abstracts = Top2Vec.load('abstracts_umap35_mincount30')
titles = Top2Vec.load('titles_umap35_vectorsize200_mincount30')

In [3]:
w,s,n = abstracts.get_topics(reduced=False)
num_top = abstracts.get_num_topics()
print(num_top)
print(s.sum()/(50*num_top))
tit_num_top = titles.get_num_topics()
print(tit_num_top)
w,s,n = titles.get_topics()
print(s.sum()/(50*tit_num_top))

201
0.42141859064054726
225
0.34753467881944444


In [4]:
# Topic reductioUMAP & hdbscann for both
abstracts.hierarchical_topic_reduction(11)
titles.hierarchical_topic_reduction(11)

[[10, 215, 1, 86, 0, 51, 60, 107, 181, 32, 184, 33, 98, 168, 2],
 [196,
  114,
  41,
  171,
  161,
  113,
  197,
  159,
  83,
  202,
  205,
  42,
  187,
  128,
  206,
  141,
  204,
  127,
  116,
  180,
  74,
  56,
  166,
  210,
  115,
  47,
  43,
  21,
  131,
  25,
  59,
  222,
  55],
 [162,
  34,
  110,
  217,
  134,
  92,
  29,
  158,
  170,
  120,
  223,
  99,
  139,
  203,
  216,
  66,
  147,
  117,
  64,
  4,
  144,
  143,
  90,
  22,
  179,
  49,
  12],
 [198,
  123,
  11,
  174,
  100,
  201,
  186,
  121,
  122,
  23,
  133,
  44,
  71,
  137,
  193,
  154,
  85,
  88,
  163,
  46,
  81,
  16,
  69,
  188,
  24,
  169,
  67,
  63],
 [38, 9, 189, 62, 87, 112, 72, 8, 145, 103, 91, 68, 118, 94, 220, 136, 75],
 [5,
  146,
  97,
  224,
  173,
  167,
  191,
  17,
  157,
  48,
  155,
  150,
  125,
  165,
  80,
  152,
  54,
  31,
  151,
  73],
 [50,
  140,
  208,
  219,
  148,
  211,
  176,
  194,
  124,
  199,
  207,
  77,
  37,
  183,
  138,
  209,
  79,
  93,
  104,
  129,
  119,
  

In [5]:
# Looking at the size of each topic ie. how many documents in each topic
abstracts.get_topic_sizes(reduced=True)

(array([7130, 7060, 7004, 6773, 6160, 5599, 4930, 4597, 4475, 4411, 4315]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [6]:
titles.get_topic_sizes(reduced=True)

(array([8199, 6483, 6165, 6113, 5903, 5466, 5357, 5149, 4870, 4453, 4296]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

In [7]:
# document_scores, document_ids=abstracts.search_documents_by_topic(topic_num=0,reduced=True,
#                                                             num_docs=lst[0],return_documents=False)
# document_ids

In [8]:
abst=[]
# size of each topic in abstracts
lst=[7130, 7060, 7004, 6773, 6160, 5599, 4930, 4597, 4475, 4411, 4315]
    
for i in range(11): 
    # Append an empty sublist inside the list with value 0
    abst.append([0]*62454) 
    
for i in range(11):
    #get document-ids for each topic
    document_scores, document_ids=abstracts.search_documents_by_topic(topic_num=i,reduced=True,
                                                            num_docs=lst[i],return_documents=False)
# go through by each docids and set it to 1 while rest are 0
    for k in document_ids:
#         print(k)
        abst[i][k]=1 
# abst[0][26929]

0

In [9]:
title=[]
# size of each topic in titles
lst_tit=[8199, 6483, 6165, 6113, 5903, 5466, 5357, 5149, 4870, 4453, 4296]
for i in range(11): 
    # Append an empty sublist inside the list 
    title.append([0]*62454) 
    
for i in range(11):
        # Append an empty sublist inside the list with value 0
    document_scores, document_ids=titles.search_documents_by_topic(topic_num=i,reduced=True,
                                                            num_docs=lst_tit[i],return_documents=False)
# go through by each docids and set it to 1 while rest are 0
    for k in document_ids:
#       print(k)
        title[i][k]=1 
    


In [15]:
result=[]
for i in range(11):
    for j in range(11):
        print('Abstract topic',i, " Title topic", j)
        print(stats.spearmanr(abst[i],title[j]))
     

Abstract topic 0  Title topic 0
SpearmanrResult(correlation=-0.11406103882125622, pvalue=7.204481467684583e-180)
Abstract topic 0  Title topic 1
SpearmanrResult(correlation=0.020779130130323023, pvalue=2.065686477909478e-07)
Abstract topic 0  Title topic 2
SpearmanrResult(correlation=0.0034062417622181527, pvalue=0.39464024574593803)
Abstract topic 0  Title topic 3
SpearmanrResult(correlation=0.043904832041739804, pvalue=4.917101166495353e-28)
Abstract topic 0  Title topic 4
SpearmanrResult(correlation=0.017570509826252724, pvalue=1.1269478206154142e-05)
Abstract topic 0  Title topic 5
SpearmanrResult(correlation=0.009795632986083248, pvalue=0.014364503260794829)
Abstract topic 0  Title topic 6
SpearmanrResult(correlation=0.003851926623159862, pvalue=0.335742515631276)
Abstract topic 0  Title topic 7
SpearmanrResult(correlation=0.025293736524917742, pvalue=2.582135656800615e-10)
Abstract topic 0  Title topic 8
SpearmanrResult(correlation=0.03098725116144082, pvalue=9.508189398542257e-1

SpearmanrResult(correlation=0.03401005858293272, pvalue=1.8687551692011413e-17)
Abstract topic 6  Title topic 9
SpearmanrResult(correlation=-0.019271418771373387, pvalue=1.4614776045367072e-06)
Abstract topic 6  Title topic 10
SpearmanrResult(correlation=0.05252843150065031, pvalue=2.0455114032361477e-39)
Abstract topic 7  Title topic 0
SpearmanrResult(correlation=-0.10776141079992146, pvalue=1.1720481390335701e-160)
Abstract topic 7  Title topic 1
SpearmanrResult(correlation=0.012627355627352493, pvalue=0.0016009170743218736)
Abstract topic 7  Title topic 2
SpearmanrResult(correlation=0.04013159882221665, pvalue=1.0909609209344944e-23)
Abstract topic 7  Title topic 3
SpearmanrResult(correlation=0.14197854138438099, pvalue=1.555091843617319e-278)
Abstract topic 7  Title topic 4
SpearmanrResult(correlation=-0.004296195425026777, pvalue=0.2829854082823941)
Abstract topic 7  Title topic 5
SpearmanrResult(correlation=-0.031099951737362932, pvalue=7.613533895418007e-15)
Abstract topic 7  Ti